dist: xenial

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qy lxc libvirt-daemon-system python3-pip  wireshark-common apache2 acl python-psycopg2 libpq-dev postgresql tomcat8 libpostgresql-jdbc-java
  - sudo systemctl start postgresql
  - sudo pip install ansible
  - sudo apt-get purge mysql-server*

script:
  - wget -O /home/travis/build/Greencorecr/alfresco_ansible/alfresco52/files/alfresco-community-installer-201707-linux-x64.bin https://download.alfresco.com/release/community/201707-build-00028/alfresco-community-installer-201707-linux-x64.bin
  - "ansible -i inventory/hosts.example --list-hosts all"
  - "ansible-playbook -i inventory/hosts.example --syntax-check *yml"
  - "ansible-playbook -i inventory/hosts.example -C *yml"
  - "ansible-playbook -i inventory/hosts.example *yml"