dist: xenial

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get purge mysql-server*
  - sudo apt-get install -qy python3-pip python-psycopg2 libpq-dev postgresql libpostgresql-jdbc-java python-pymysql mariadb-server
  - sudo systemctl start postgresql
  - sudo systemctl start mysql.service
  - sudo pip install ansible psutil molecule

script:
  - for dir in alfresco_base alfresco_install alfresco_uninstall alfresco_backup alfresco_restore; do ( cd $dir ; molecule lint ) ; done
  - ansible -i inventory/hosts-travis-upgrade.yml --list-hosts all
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml --syntax-check *yml
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml install_alfresco52-pgsql_no_docker.yml
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml backup-immediate.yml
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml uninstall_alfresco.yml
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml install_alfresco52-pgsql_no_docker.yml
  - ansible-playbook -i inventory/hosts-travis-upgrade.yml restore-immediate.yml
