---
# tasks file for alfresco6.1

#    - fail:
#      name: Revisa si estamos en Bionic, excepto en travis (quien no tiene bionic)
#        msg: "La guía solo aplica para Ubuntu Bionic"
#      when: (travisenv != "true") and (ansible_distribution_release != "bionic")
    - name: Instala aptitude (requerido por ansible)
      apt:
        name: aptitude
        state: latest
        update_cache: yes
      become: yes
    - name: Actualiza cache
      apt:
        update_cache: yes
      become: yes
    - name: Actualiza paquetes
      apt:
        upgrade: dist
      become: yes
      ignore_errors: true
    - name: autoremueve
      apt:
        autoremove: yes
      become: yes
    - name: Instala paquetes adicionales
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jre
        - tomcat8
        - libreoffice
        - imagemagick
        - postgresql
        - postgresql-client-common
        - libpostgresql-jdbc-java
        - unzip
        - python3-pip
        - python-psycopg2 # Para ansible+postgresql
        - libpq-dev       # Para ansible+postgresql
      become: yes
    - name: Agrega usuario para solr
      user:
        name: solr
        state: present
        create_home: false
        password_lock: true
        system: true
      become: yes
    - name: Descarga e instala Alfresco PDF Render para GNU/Linux
      unarchive:
        src: https://artifacts.alfresco.com/nexus/content/repositories/public/org/alfresco/alfresco-pdf-renderer/1.1/alfresco-pdf-renderer-1.1-linux.tgz
        dest: /usr/local/bin
        remote_src: yes
      become: yes
    - name: Agrega archivo de config para servicio Solr
      copy:
        src: "{{ role_path }}/files/solr.service"
        dest: /etc/systemd/system/solr.service
        owner: root
        mode: 0644
      become: yes
    - name: Reinicia systemd luego de cambiar configuración
      systemd:
        daemon_reload: yes
      become: yes
    - name: Configura servicios
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - tomcat8
        - postgresql.service
        #- solr
      become: yes
    - name: Crea directorios para instalación
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - /srv/alfresco
        - /srv/solr
        - /var/lib/tomcat8/webapps/shared/classes
        - /var/lib/tomcat8/webapps/shared/lib
      become: yes
    - name: Crea liga para librerías de postgresql en tomcat
      file:
        src: /usr/share/java/postgresql.jar
        dest: /var/lib/tomcat8/webapps/shared/lib/postgresql.jar
        state: link
        mode: 0755
      become: yes
    - name: Crea usuario de PosgreSQL para Alfresco
      postgresql_user:
        name: alfresco
        password: alfresco # TODO: Manejar con include a ansible vault
        state: present
    - name: Crea base de datos para Alfresco
      postgresql_db:
        name: alfresco
        owner: alfresco
    - name: Detiene Tomcat para instalar aplicación
      service:
        name: tomcat8
        state: stopped
      become: yes
    - name: Descarga Alfresco content-services-community e instala en Tomcat
      unarchive:
        url: https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/content-services-community/6.1.2-ga/content-services-community-6.1.2-ga.war
        dest: /var/lib/tomcat8/webapps/
        mode: 0755
        owner: tomcat8
        group: root
      become: yes