---
# tasks file for alfresco52
    - fail:
        msg: "La guía solo aplica para Ubuntu Bionic"
      when: ansible_distribution_release != "bionic"
    - name: Instala aptitude (requerido por ansible)
      apt:
        name: aptitude
        state: latest
        update_cache: yes
      become: yes
    - name: Actualiza cache
      apt:
        update_cache: yes
      become: yes
    - name: Actualiza paquetes
      apt:
        upgrade: dist
      become: yes
      ignore_errors: true
    - name: autoremueve
      apt:
        autoremove: yes
      become: yes
    - name: Instala paquetes adicionales
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jre
        - tomcat8
        - libreoffice
        - imagemagick
        - postgresql-server
      become: yes