---
- name: Instala paquetes requeridos
  apt:
    name:
      - postgresql-client-common
      - postgresql-client-10
    state: present
  become: yes
- name: Respalda {{ solr4_root }} y almancena en HOME
  vars:
    filename: "alfresco-{{ inventory_hostname }}-solr4.tar.bz2"
  archive:
    path: "{{ alf_root }}"
    dest: "/{{ ansible_env.HOME }}/{{ filename }}"
    format: bz2
  become: true
- name: Respalda base de datos Alfresco, y almancena en HOME
  postgresql_db:
    name: alfresco
    state: dump
    login_user: alfresco
    login_password: "greencore"
    login_host: localhost
    login_unix_socket: /tmp/ 
    target: "/{{ ansible_env.HOME }}/alfresco-{{ inventory_hostname }}.sql"
- name: Respalda {{ alf_root }} y almancena en HOME
  vars:
    filename: "alfresco-{{ inventory_hostname }}-full.tar.bz2"
  archive:
    path: "{{ alf_root }}"
    dest: "/{{ ansible_env.HOME }}/{{ filename }}"
    format: bz2
  become: true
