---
- name: Respalda {{ solr4_root }} y almancena en HOME
  vars:
    solr_filename: "alfresco-{{ inventory_hostname }}-solr4.tar.bz2"
  archive:
    path: "{{ solr4_root }}"
    dest: "/{{ ansible_env.HOME }}/{{ solr_filename }}"
    format: bz2
  become: true
- name: Respalda base de datos Alfresco, y almancena en HOME
  postgresql_db:
    name: alfresco
    state: dump
    login_user: alfresco
    login_password: "greencore"
    login_host: localhost
    login_unix_socket: /tmp/
    target: "/{{ ansible_env.HOME }}/alfresco-{{ inventory_hostname }}.sql"
- name: Respalda {{ alf_root }} y almancena en HOME/{{ root_filename }}
  vars:
    root_filename: "alfresco-{{ inventory_hostname }}-root.tar.bz2"
  archive:
    path: "{{ dir_root }}"
    dest: "/{{ ansible_env.HOME }}/{{ root_filename }}"
    format: bz2
  become: true
